#jika abis di bagi 3 fizz, jika abis dibagi 5 buzz, jika abis dibagi 3 dan 5 fizzbuzz
def fizz_buzz(input):
    if (input % 3 == 0) and (input % 5 == 0):
        return "fizzbuzz"
    if (input % 3 == 0):
        return "fizz"
    if (input % 5 == 0):
        return "buzz"
    
    return (input)    
    
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(15))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))
print (fizz_buzz(10))